In [5]:
'''Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2'''
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr)
new_arr=arr+2
print(new_arr)
arr2= arr*3
print(arr2)
arr3= arr/2
print(arr3)

[1 2 3 4 5]
[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [ ]:
'''Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])'''
arr= np.array([1,2,3,6,4,5])
reversed= np.flip(arr)
print(reversed)
import numpy as np

def most_frequent(arr):
    unique, counts = np.unique(arr, return_counts=True)  
    max_count = np.max(counts)  
    most_frequent_value = unique[np.argmax(counts)] 
    indices = np.where(arr == most_frequent_value)[0] 
    return most_frequent_value, indices
x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
x_value, x_indices = most_frequent(x)
y_value, y_indices = most_frequent(y)
print(f"Most frequent value in x: {x_value}, Indices: {x_indices}")
print(f"Most frequent value in y: {y_value}, Indices: {y_indices}")



[5 4 6 3 2 1]
Most frequent value in x: 1, Indices: [0 5 7 8 9]
Most frequent value in y: 1, Indices: [0 1 2]


In [12]:
'''Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column'''

arr1= np.array([[10,20,30],
               [40,50,60],
               [70,80,90]])
element_a = arr1[0, 1]  
print("1st row, 2nd column:", element_a)
element_b = arr1[2, 0]  
print("3rd row, 1st column:", element_b)





1st row, 2nd column: 20
3rd row, 1st column: 70


In [2]:
'''Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?'''

import numpy as np
RIDHI = np.linspace(10, 100, 25)

print("Array:", RIDHI)
print("Dimensions:", RIDHI.ndim) 
print("Shape:", RIDHI.shape)  
print("Total Elements:", RIDHI.size)  
print("Data Type of Elements:", RIDHI.dtype)  
print("Total Bytes Consumed:", RIDHI.nbytes)  


transposed_array = RIDHI.reshape(25, 1)
print(transposed_array)

print(RIDHI.T) 

print(np.array_equal(transposed_array, RIDHI.T))

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total Elements: 25
Data Type of Elements: float64
Total Bytes Consumed: 200
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
False


In [3]:
'''Q5. Create a 2-D Array of three rows and four columns, named ucs420_<your_name>>
with following values – 10, 20, 30, 40, 50, 60, 70, 80, 90, 15, 20, 35. Compute the mean,
median, max, min, unique elements. Reshape the array to four rows and three columns and
name it as reshaped_ ucs420_<your_name>>. Resize the array to two rows and three
columns and name it as resized_ ucs420_<your_name>>.'''

ucs420_Ridhi = np.array([
    [10, 20, 30, 40], 
    [50, 60, 70, 80], 
    [90, 15, 20, 35]
])
mean_value = np.mean(ucs420_Ridhi)     
median_value = np.median(ucs420_Ridhi)  
reshaped_ucs420_Ridhi = ucs420_Ridhi.reshape(4, 3)
max_value = np.max(ucs420_Ridhi)        
min_value = np.min(ucs420_Ridhi)         
unique_values = np.unique(ucs420_Ridhi)  
reshaped_ucs420_Ridhi = ucs420_Ridhi.reshape(4, 3)
resized_ucs420_Ridhi = np.resize(ucs420_Ridhi, (2, 3))
print("Original 3x4 Array (ucs420_):\n", ucs420_Ridhi)
print("\nMean:", mean_value)
print("Median:", median_value)
print("Max Value:", max_value)
print("Min Value:", min_value)
print("Unique Elements:", unique_values)
print("\nReshaped (4x3) Array:\n", reshaped_ucs420_Ridhi)
print("\nResized (2x3) Array:\n", resized_ucs420_Ridhi)


Original 3x4 Array (ucs420_):
 [[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]

Mean: 43.333333333333336
Median: 37.5
Max Value: 90
Min Value: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped (4x3) Array:
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized (2x3) Array:
 [[10 20 30]
 [40 50 60]]
